version: '3'

services:
  node:
    build: docker/node
    working_dir: /srv
    volumes:
      - .:/srv
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Entrypoint
      - ./docker/node/entrypoint-node.sh:/usr/local/bin/entrypoint.sh:ro
    entrypoint: entrypoint.sh
